name: book-management-system-ci

on:
  push:
    branches:
      - product

jobs:
  build-with-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: production 브랜치로 이동
        uses: actions/checkout@v3
        with:
          ref: product

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: gradlew 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 프로젝트 빌드
        run: ./gradlew clean build -x test
